### ISSUE TITLE
User with GoogleAuthenticator is not prompted for 2FA.

### ISSUE THREAD

**Issue by nmg196** [jerriep/jerriepelser.com#14]
I've followed the instructions in the article and at first I thought everything was working OK, but if sign in (even on a new browser), I'm not prompted for the 2FA information - it just signs me in.

It seems the default SignInAsync doesn't check the "IsGoogleAuthenticatorEnabled" flag and just returns "Success".  Have I missed something or is a custom override of SignInAsync needed to get this working as expected?

Thanks,
Nick

**Comment by jerriep** [comment]
Please ask for support on a site dedicated to it, such as StackOverflow

**Comment by nmg196** [comment]
It's OK - I figured it out.  There is a mistake in the example.
