### ISSUE TITLE
Replace blog: Forcing user to sign in with their Google Organization (G Suite) account

### ISSUE THREAD

**Issue by pwen090** [jerriep/jerriepelser.com#20]
https://www.jerriepelser.com/blog/forcing-users-sign-in-gsuite-domain-account/

You do not need to write custom code, which is going to be error prone/bad for security, to restrict access to your specific gsuite domain. You simply need to set the API the OAuth application type to Internal within your Google Console for Developers:

![image](https://user-images.githubusercontent.com/19834208/61158207-28a96b80-a4ad-11e9-8f67-fd7a8663e92e.png)

This will make it so that Google denies anyone logging into your asp.net core app that is not from your gsuite domain.

**Comment by jerriep** [comment]
This blog post is old. I believe at the time I wrote that blog post this was not possible

**Comment by jerriep** [comment]
Also, I believe there are valid cases where you may want to ensure a user is from a domain which may not be your own
