### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by filipw** [jerriep/jerriepelser.com#4]
did you disappear from Twitter? I tried to tag you but @jerriepelser gives me a 404 😱

**Comment by jerriep** [comment]
@filipw Yes, I left Twitter about 2 years ago. At the time I decided to become a dark-matter programmer, but have since resurfaced in a few places ;)

**Comment by jerriep** [comment]
@filipw Hey Filip, just a quick note that your RSS feed on your website appears to be broken. Last post showing up in the RSS feed is from 8 Dec.

When you have a chance, can you look into it, please?
