### ISSUE TITLE
Wrong Code

### ISSUE THREAD

**Issue by DLMANSOFT** [jerriep/jerriepelser.com#8]
Hello
I have gone through the [guidance ](https://www.jerriepelser.com/blog/using-google-authenticator-asp-net-identity/)and implemented everything well.
But in most cases,on service activation show "The Code is not valid" message and user can not activate the service.
please help me.

**Comment by jerriep** [comment]
Please ask support questions on Stackoverflow. I have not worked with this for many years and cannot help you
